### ISSUE TITLE
Issue with CRLF in sites.yaml

### ISSUE THREAD

**Issue by loviuz** [Findus23/rss2wallabag#45]
Hi, i have added this source to sites.yaml:

```
PortSwigger:
  filter: null
  github: null
  latest_article: US court order brings down the shutters on tech support scheme impacting
    the elderly
  tags:
  - english
  - hacking
  url: https://portswigger.net/daily-swig/rss
```

On "latest_article:" the title has been saved with carriage return, so I think the next time the download will occur I will get an error :-/
